application: xml2csv
version: 3
runtime: python
api_version: 1

handlers:
- url: /(favicon\.(ico|gif)|robots\.txt|googleca0be0b46b6e1ec9\.html)
  static_files: \1
  upload: (favicon\.(ico|gif)|robots\.txt|googleca0be0b46b6e1ec9\.html)

- url: .*
  script: main.py
